# Generated by Django 4.2.7 on 2023-12-10 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednotification',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 14, 37, 3, 376130, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
