# Generated by Django 4.2.7 on 2023-11-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tag_product_image_producttag_product_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='admin_user_id',
            new_name='admin_user',
        ),
    ]
